INFO 2012-11-27 13:25:34,572 utils 32246 4572692480 Finished tagging source from: http://www.nytimes.com/2012/11/27/us/politics/politics-in-play-over-safety-net-in-deficit-talks.html?hp&_r=0 
INFO 2012-11-27 13:27:17,875 utils 32250 4325273600 Finished tagging source from: http://www.nytimes.com/2012/11/27/us/politics/politics-in-play-over-safety-net-in-deficit-talks.html?hp&_r=0 
INFO 2012-11-28 11:52:37,943 utils 32794 4488208384 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 11:54:37,073 utils 32795 4414652416 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 119, in slip
    replaced = replace_document_words(tx, tagged_text, SEXWORDS)
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 80, in replace_document_words
    if w[0].isupper(): rp[0] = rp[0].upper()
TypeError: 'unicode' object does not support item assignment

INFO 2012-11-28 11:54:37,099 utils 32795 4414652416 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 11:56:08,754 utils 32796 4306464768 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 119, in slip
    replaced = replace_document_words(tx, tagged_text, SEXWORDS)
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 80, in replace_document_words
    if w[0].isupper(): rp[0] = rp.upper()[0]
TypeError: 'unicode' object does not support item assignment

INFO 2012-11-28 11:56:08,776 utils 32796 4306464768 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 11:58:57,918 utils 32798 4458938368 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 13:26:23,205 utils 32841 4492730368 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 14:07:52,647 utils 32871 4431052800 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 14:08:17,579 utils 32871 4431052800 Finished tagging source from: http://bbc.co.uk/ 
INFO 2012-11-28 14:30:57,206 utils 32881 4533972992 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 14:31:18,732 utils 32881 4533972992 Finished tagging source from: http://www.bbc.co.uk/news/world-middle-east-20523039 
INFO 2012-11-28 14:37:53,119 utils 32908 4543070208 Finished tagging source from: http://www.bbc.co.uk/news/world-middle-east-20523039 
INFO 2012-11-28 15:03:14,714 utils 32941 4395679744 Getting source from: http://www.bbc.co.uk/news/video_and_audio/
INFO 2012-11-28 15:03:15,073 utils 32941 4395679744 Got 200 response from http://www.bbc.co.uk/news/video_and_audio/
INFO 2012-11-28 15:03:25,081 utils 32941 4395679744 Finished tagging source from: http://www.bbc.co.uk/news/video_and_audio/ 
INFO 2012-11-28 15:19:05,176 utils 32958 4486393856 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:19:07,068 utils 32958 4486393856 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:19:23,030 utils 32958 4486393856 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:19:49,448 utils 32964 4339429376 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:19:49,751 utils 32964 4339429376 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:20:05,485 utils 32964 4339429376 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:20:24,142 utils 32965 4327759872 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:20:24,737 utils 32965 4327759872 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:20:41,344 utils 32965 4327759872 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:20:48,363 utils 32966 4374732800 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:20:48,602 utils 32966 4374732800 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:21:04,436 utils 32966 4374732800 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:21:19,814 utils 32967 4327903232 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:21:20,050 utils 32967 4327903232 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:21:35,609 utils 32967 4327903232 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:37:30,490 utils 32982 4325933056 Getting source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:37:30,680 utils 32982 4325933056 Could not get source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:37:30,711 utils 32982 4325933056 Error stack 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 24, in get_source
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 392, in open
    req = meth(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1100, in do_request_
    raise URLError('no host given')
URLError: <urlopen error no host given>

INFO 2012-11-28 15:39:17,267 utils 32984 4361666560 Getting source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:39:17,318 utils 32984 4361666560 Could not get source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:39:17,339 utils 32984 4361666560 Error stack 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 24, in get_source
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 392, in open
    req = meth(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1100, in do_request_
    raise URLError('no host given')
URLError: <urlopen error no host given>

INFO 2012-11-28 15:40:10,706 utils 32985 4465938432 Getting source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:40:10,710 utils 32985 4465938432 Could not get source from: http:///bbc.co.uk/
ERROR 2012-11-28 15:40:10,711 utils 32985 4465938432 Error stack 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 24, in get_source
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 392, in open
    req = meth(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1100, in do_request_
    raise URLError('no host given')
URLError: <urlopen error no host given>

INFO 2012-11-28 15:42:59,854 utils 32986 4392992768 Getting source from: http://bbc.co.uk/
INFO 2012-11-28 15:43:01,651 utils 32986 4392992768 Got 200 response from http://bbc.co.uk/
INFO 2012-11-28 15:56:21,098 utils 33007 4440633344 Getting source from: http://bbc.co.uk
INFO 2012-11-28 15:56:22,788 utils 33007 4440633344 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 15:56:36,045 utils 33007 4440633344 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 15:59:27,047 utils 33007 4440633344 Getting source from: http://www.bbc.co.uk/news/uk-politics-20524115
INFO 2012-11-28 15:59:27,270 utils 33007 4440633344 Got 200 response from http://www.bbc.co.uk/news/uk-politics-20524115
INFO 2012-11-28 15:59:34,936 utils 33007 4440633344 Finished tagging source from: http://www.bbc.co.uk/news/uk-politics-20524115 
INFO 2012-11-28 17:18:45,593 utils 33056 4382695424 Getting source from: http://bbc.co.uk
INFO 2012-11-28 17:18:46,409 utils 33056 4382695424 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 17:19:02,276 utils 33056 4382695424 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-28 17:20:41,264 utils 33061 4408619008 Getting source from: http://bbc.co.uk
INFO 2012-11-28 17:20:43,345 utils 33061 4408619008 Got 200 response from http://bbc.co.uk
INFO 2012-11-28 17:20:59,265 utils 33061 4408619008 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 14:35:19,384 utils 33507 4553134080 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:35:20,044 utils 33507 4553134080 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:35:21,217 utils 33507 4553134080 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 126, in slip
    t['href'] = reverse('slip_freudify_url', kwargs = { 'url': t['href'] })
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'

INFO 2012-11-29 14:39:03,865 utils 33508 4498612224 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:39:04,422 utils 33508 4498612224 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:39:05,402 utils 33508 4498612224 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 126, in slip
    t['href'] = reverse('slip_freudify_url', kwargs = { 'url': t['href'] })
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'

INFO 2012-11-29 14:40:54,525 utils 33510 4533735424 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:40:55,221 utils 33510 4533735424 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:40:56,314 utils 33510 4533735424 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 125, in slip
    if 'href' in t.keys():
TypeError: 'NoneType' object is not callable

INFO 2012-11-29 14:42:47,108 utils 33511 4412260352 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:42:47,657 utils 33511 4412260352 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:42:47,962 utils 33511 4412260352 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 126, in slip
    if 'href' in t.keys():
TypeError: 'NoneType' object is not callable

INFO 2012-11-29 14:43:26,081 utils 33512 4377231360 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:43:26,620 utils 33512 4377231360 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:43:27,451 utils 33512 4377231360 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 127, in slip
    t['href'] = reverse('slip_freudify_url', kwargs = { 'url': t['href'] })
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'

INFO 2012-11-29 14:43:43,718 utils 33512 4377231360 Getting source from: http://bbc.co.uk
INFO 2012-11-29 14:43:45,854 utils 33512 4377231360 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 14:44:01,619 utils 33512 4377231360 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 14:52:03,090 utils 33512 4377231360 Getting source from: http://bbc.co.uk
INFO 2012-11-29 14:52:04,034 utils 33512 4377231360 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 14:52:16,070 utils 33512 4377231360 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 14:56:30,814 utils 33518 4323123200 Getting source from: http://gutenberg.org
INFO 2012-11-29 14:56:31,841 utils 33518 4323123200 Got 200 response from http://gutenberg.org
INFO 2012-11-29 14:56:36,671 utils 33518 4323123200 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:10:46,915 utils 33528 4506423296 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:10:47,939 utils 33528 4506423296 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:10:52,786 utils 33528 4506423296 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:12:40,575 utils 33529 4483768320 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:12:41,121 utils 33529 4483768320 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:12:41,932 utils 33529 4483768320 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 124, in slip
    if t.name == 'a' and 'href' in t.attrs:
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 667, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'Comment' object has no attribute 'name'

INFO 2012-11-29 15:13:20,466 utils 33530 4490412032 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:13:21,012 utils 33530 4490412032 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:13:26,096 utils 33530 4490412032 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:19:03,726 utils 33534 4542894080 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:19:04,277 utils 33534 4542894080 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:19:09,131 utils 33534 4542894080 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:32:36,996 utils 33545 4386168832 Getting source from: http://bbc.co.uk
INFO 2012-11-29 15:32:38,598 utils 33545 4386168832 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 15:32:53,725 utils 33545 4386168832 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 15:33:12,611 utils 33545 4386168832 Getting source from: http://gutenberg.og
ERROR 2012-11-29 15:33:13,616 utils 33545 4386168832 Could not get source from: http://gutenberg.og
ERROR 2012-11-29 15:33:13,631 utils 33545 4386168832 Error stack 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 25, in get_source
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1199, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1174, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

INFO 2012-11-29 15:33:19,113 utils 33545 4386168832 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:33:19,832 utils 33545 4386168832 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:33:20,659 utils 33545 4386168832 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 130, in slip
    t['href'] = reverse('slip_freudify_url', kwargs = { 'url': t['href'] })
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'

INFO 2012-11-29 15:34:07,913 utils 33557 4567310336 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:34:08,452 utils 33557 4567310336 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:34:13,895 utils 33557 4567310336 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:41:47,855 utils 33564 4506243072 Getting source from: http://bbc.co.uk
INFO 2012-11-29 15:41:49,473 utils 33564 4506243072 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 15:41:50,166 utils 33564 4506243072 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 132, in slip
    t['href'] = urljoin(url, t['href'])
  File "/Library/Python/2.7/site-packages/bs4/element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'

INFO 2012-11-29 15:42:27,040 utils 33565 4549509120 Getting source from: http://bbc.co.uk
INFO 2012-11-29 15:42:27,248 utils 33565 4549509120 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 15:42:42,678 utils 33565 4549509120 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 15:57:29,922 utils 33565 4549509120 Getting source from: http://gutenberg.org
INFO 2012-11-29 15:57:30,968 utils 33565 4549509120 Got 200 response from http://gutenberg.org
INFO 2012-11-29 15:57:32,402 utils 33565 4549509120 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 15:59:18,026 utils 33565 4549509120 Getting source from: http://bbc.co.uk
INFO 2012-11-29 15:59:19,641 utils 33565 4549509120 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 15:59:29,261 utils 33565 4549509120 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 16:00:26,610 utils 33565 4549509120 Getting source from: http://www.bbc.co.uk/news/health-20526380
INFO 2012-11-29 16:00:26,739 utils 33565 4549509120 Got 200 response from http://www.bbc.co.uk/news/health-20526380
INFO 2012-11-29 16:00:34,870 utils 33565 4549509120 Finished tagging source from: http://www.bbc.co.uk/news/health-20526380 
INFO 2012-11-29 16:42:16,390 utils 33601 4404150272 Getting source from: http://bbc.co.uk
INFO 2012-11-29 16:42:18,033 utils 33601 4404150272 Got 200 response from http://bbc.co.uk
INFO 2012-11-29 16:42:34,868 utils 33601 4404150272 Finished tagging source from: http://bbc.co.uk 
INFO 2012-11-29 16:42:52,132 utils 33601 4404150272 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:42:52,814 utils 33601 4404150272 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:42:54,525 utils 33601 4404150272 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 16:44:02,538 utils 33603 4364525568 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:44:03,124 utils 33603 4364525568 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:44:07,664 utils 33603 4364525568 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 16:44:40,188 utils 33604 4332670976 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:44:40,734 utils 33604 4332670976 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:44:45,354 utils 33604 4332670976 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 16:47:08,591 utils 33605 4375912448 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:47:09,135 utils 33605 4375912448 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:47:14,197 utils 33605 4375912448 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 16:47:56,505 utils 33606 4483694592 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:47:57,095 utils 33606 4483694592 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:47:58,274 utils 33606 4483694592 utils.slip has blown, with message: 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 135, in slip
    for m in re.finditer(r"@import(\s+)\"(.*)\"", t.contents):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 186, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or buffer

INFO 2012-11-29 16:50:52,642 utils 33607 4537171968 Getting source from: http://gutenberg.org
INFO 2012-11-29 16:50:53,203 utils 33607 4537171968 Got 200 response from http://gutenberg.org
INFO 2012-11-29 16:50:58,216 utils 33607 4537171968 Finished tagging source from: http://gutenberg.org 
INFO 2012-11-29 16:56:33,167 utils 33629 4459565056 Getting source from: http://gutenberg.org
ERROR 2012-11-29 16:56:33,814 utils 33629 4459565056 Could not get source from: http://gutenberg.org
ERROR 2012-11-29 16:56:33,816 utils 33629 4459565056 Error stack 
 Traceback (most recent call last):
  File "/Users/slinkola/Koulu/lhhc/Slipper/../Slipper/slip/utils.py", line 25, in get_source
    response = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

